services:
  # ---------------------------------------------------------
  # SCADA Masters (The Client polling the network)
  # ---------------------------------------------------------
  scada_master:
    build:
      context: .
      args:
        SCRIPT_NAME: async_scada.py
    command: ['/app/scripts/async_scada.py', '--target', '10.30.0.3:5020', '--count', '2']
    container_name: scada1
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.8  # Assign a static IP on your physical subnet

  scada2:
    build:
      context: .
      args:
        SCRIPT_NAME: async_scada.py
    command: ['/app/scripts/async_scada.py', '--target', ' 10.30.0.3:5020', '--count', '2']
    container_name: scada2
    networks: 
      grid_macvlan:
        ipv4_address: 10.30.0.17

  scada3:
    build:
      context: .
      args:
        SCRIPT_NAME: async_scada.py
    command: ['/app/scripts/async_scada.py', '--target', ' 10.30.0.5:5020', '--count', '2']
    container_name: scada3
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.32

  scada4:
    build:
      context: .
      args:
        SCRIPT_NAME: async_scada.py
    command: ['/app/scripts/async_scada.py', '--target', ' 10.30.0.5:5020', '--count', '2']
    container_name: scada4
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.28

  # ---------------------------------------------------------
  # Historian Loggers
  # ---------------------------------------------------------
  historian_logger:
    build:
      context: .
      args:
        SCRIPT_NAME: historian_logger.py
    command: ['/app/scripts/historian_logger.py', '--target', '10.30.0.3:5020']
    container_name: historian_logger1
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.10

  historian_logger2:
    build:
      context: .
      args:
        SCRIPT_NAME: historian_logger.py
    command: ['/app/scripts/historian_logger.py', '--target', '10.30.0.3:5020']
    container_name: historian_logger2
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.33

  historian_logger3:
    build:
      context: .
      args:
        SCRIPT_NAME: historian_logger.py
    command: ['/app/scripts/historian_logger.py', '--target', '10.30.0.5:5020']
    container_name: historian_logger3
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.49

  historian_logger4:
    build:
      context: .
      args:
        SCRIPT_NAME: historian_logger.py
    command: ['/app/scripts/historian_logger.py', '--target', '10.30.0.5:5020']
    container_name: historian_logger4
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.22

  # ---------------------------------------------------------
  # Attacker Containers
  # ---------------------------------------------------------
  DOS_Attack:
    build:
      context: .
      args:
        SCRIPT_NAME: DOS_Attack_Sim.py
    command: ['/app/scripts/DOS_Attack_Sim.py']
    container_name: DOS1
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.43

  read_bulk:
    build:
      context: .
      args:
        SCRIPT_NAME: read_bulk.py
    command: ['/app/scripts/read_bulk.py', '10.30.0.3']
    container_name: read_bulk1
    networks:
      grid_macvlan:
        ipv4_address: 10.30.0.11

# ---------------------------------------------------------
# Network Configuration (CRITICAL STEP)
# ---------------------------------------------------------
networks:
  grid_macvlan:
    driver: macvlan
    driver_opts:
      # VM's primary interface facing pfSense
      parent: ens18
    ipam:
      config:
        - subnet: "10.30.0.0/24"     # physical network subnet
          gateway: "10.30.0.254"       # pfSense IP address
          ip_range: "10.30.0.192/30"
